# Generated by Django 4.2.14 on 2024-09-13 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('volcano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volcano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fall_directions', related_query_name='fall_direction', to='volcano.volcano')),
            ],
            options={
                'verbose_name': 'Fall Direction',
                'verbose_name_plural': 'Fall Directions',
            },
        ),
        migrations.CreateModel(
            name='ObservatoryPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volcano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_posts', related_query_name='observatory_post', to='volcano.volcano')),
            ],
            options={
                'verbose_name': 'Observatory Post',
                'verbose_name_plural': 'Observatory Posts',
            },
        ),
        migrations.CreateModel(
            name='VolcanicEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('observation_form', models.CharField(blank=True, choices=[('not_observed', 'Not Observed'), ('visible', 'Visible'), ('audible', 'Audible'), ('visible_and_audible', 'Visible and Audible')], max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('gray', 'Gray'), ('black', 'Black'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('red', 'Red'), ('orange', 'Orange')], max_length=100, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volcanic_emissions', related_query_name='volcanic_emission', to='event.event')),
                ('observatory_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.observatorypost')),
            ],
            options={
                'verbose_name': 'Volcanic Emission',
                'verbose_name_plural': 'Volcanic Emissions',
            },
        ),
        migrations.CreateModel(
            name='Tectonic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('mmi_scale', models.CharField(blank=True, choices=[('I', 'I - Not felt'), ('II', 'II - Weak'), ('III', 'III - Weak'), ('IV', 'IV - Light'), ('V', 'V - Moderate'), ('VI', 'VI - Strong'), ('VII', 'VII - Very strong'), ('VIII', 'VIII - Severe'), ('IX', 'IX - Violent'), ('X', 'X - Extreme'), ('XI', 'XI - Extreme'), ('XII', 'XII - Extreme')], max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tectonics', related_query_name='tectonic', to='event.event')),
                ('observatory_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.observatorypost')),
            ],
            options={
                'verbose_name': 'Tectonic',
                'verbose_name_plural': 'Tectonics',
            },
        ),
        migrations.CreateModel(
            name='Rockfall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('is_lava_flow', models.BooleanField(default=False)),
                ('observation_form', models.CharField(blank=True, choices=[('not_observed', 'Not Observed'), ('visible', 'Visible'), ('audible', 'Audible'), ('visible_and_audible', 'Visible and Audible')], max_length=100, null=True)),
                ('event_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('not_observed', 'Not Observed')], max_length=100, null=True)),
                ('runout_distance', models.FloatField(blank=True, null=True)),
                ('amplitude', models.FloatField(blank=True, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('dip', models.FloatField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rockfalls', related_query_name='rockfall', to='event.event')),
                ('fall_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.falldirection')),
                ('observatory_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.observatorypost')),
            ],
            options={
                'verbose_name': 'Rockfall',
                'verbose_name_plural': 'Rockfalls',
            },
        ),
        migrations.CreateModel(
            name='PyroclasticFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('is_lava_flow', models.BooleanField(default=False)),
                ('observation_form', models.CharField(blank=True, choices=[('not_observed', 'Not Observed'), ('visible', 'Visible'), ('audible', 'Audible'), ('visible_and_audible', 'Visible and Audible')], max_length=100, null=True)),
                ('event_size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('not_observed', 'Not Observed')], max_length=100, null=True)),
                ('runout_distance', models.FloatField(blank=True, null=True)),
                ('estimated_distance', models.FloatField(blank=True, null=True)),
                ('amplitude', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyroclastic_flows', related_query_name='pyroclastic_flow', to='event.event')),
                ('fall_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.falldirection')),
                ('observatory_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.observatorypost')),
            ],
            options={
                'verbose_name': 'Pyroclastic Flow',
                'verbose_name_plural': 'Pyroclastic Flows',
            },
        ),
        migrations.CreateModel(
            name='Explosion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('observation_form', models.CharField(blank=True, choices=[('not_observed', 'Not Observed'), ('visible', 'Visible'), ('audible', 'Audible'), ('visible_and_audible', 'Visible and Audible')], max_length=100, null=True)),
                ('column_height', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('gray', 'Gray'), ('black', 'Black'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('red', 'Red'), ('orange', 'Orange')], max_length=100, null=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('vei', models.IntegerField(blank=True, choices=[(0, 'VEI 0'), (1, 'VEI 1'), (2, 'VEI 2'), (3, 'VEI 3'), (4, 'VEI 4'), (5, 'VEI 5'), (6, 'VEI 6'), (7, 'VEI 7'), (8, 'VEI 8')], null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explosions', related_query_name='explosion', to='event.event')),
                ('observatory_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observation.observatorypost')),
            ],
            options={
                'verbose_name': 'Explosion',
                'verbose_name_plural': 'Explosions',
            },
        ),
    ]
