# Generated by Django 4.2.17 on 2025-01-17 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyroclasticflow',
            name='fall_directions',
            field=models.ManyToManyField(blank=True, to='observation.falldirection'),
        ),
        migrations.AddField(
            model_name='rockfall',
            name='fall_directions',
            field=models.ManyToManyField(blank=True, to='observation.falldirection'),
        ),
        migrations.AlterField(
            model_name='pyroclasticflow',
            name='fall_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyroclastic_flows', to='observation.falldirection'),
        ),
        migrations.AlterField(
            model_name='rockfall',
            name='fall_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rockfalls', to='observation.falldirection'),
        ),
    ]
