# Generated by Django 4.2.17 on 2025-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_amplitude_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amplitude",
            name="amplitude",
            field=models.FloatField(
                blank=True, help_text="Measured amplitude value.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="magnitude",
            name="magnitude",
            field=models.FloatField(
                blank=True,
                help_text="\n            Resulting magnitude value from combining values of type\n            StationMagnitude. If no estimations are available, this value can\n            represent the reported magnitude.\n            ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stationmagnitude",
            name="magnitude",
            field=models.FloatField(
                blank=True, help_text="Estimated magnitude.", null=True
            ),
        ),
    ]
