# Generated by Django 4.2.16 on 2024-11-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventobserverconfig",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Order of the event observer in the list of observers.",
            ),
        ),
        migrations.AddField(
            model_name="eventobserverconfig",
            name="run_async",
            field=models.BooleanField(
                default=False,
                help_text="Run the event observer asynchronously using Celery.",
            ),
        ),
    ]
